language: dart
dart:
  - stable
addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - bash ci/before_install.sh

after_success:
  - bash ci/after_script.sh

jobs:
  include:
    - stage: test
      script: bash ci/script.sh
      env: TEST_DIR="aquedart" RUNNER_ARGS="-t cli" RUNNER_CMD="pub run test -j 1 -r expanded"
    - stage: test
      script: bash ci/script.sh
      env: TEST_DIR="aquedart" RUNNER_ARGS="-x cli" RUNNER_CMD="pub run test -j 1 -r expanded"
    - stage: test
      script: bash ci/script.sh
      env: TEST_DIR="aquedart_test" RUNNER_CMD="pub run test -j 1 -r expanded"
    - stage: test
      script: bash ci/script.sh
      env: TEST_DIR="aquedart" RUNNER_ARGS="" RUNNER_CMD="dart tool/generated_test_runner.dart"

stages:
  - test

branches:
  only:
    - master
