name: aqueduct_test
description: Utilities for writing automated tests for Aqueduct applications
version: 2.0.0-b1
homepage: https://github.com/stablekernel/aqueduct
author: stable|kernel <jobs@stablekernel.com>
documentation:
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.3.0
  matcher: '>=0.12.3 <0.14.0'
  aqueduct:
    git: 
      url: git://github.com/EddieKamau/aqueduct.git
      path: aqueduct

# # This is removed before being published.
# dependency_overrides:
#   aqueduct:
#     path: ../aqueduct