name: wildfire
description: An Aqueduct application with a database connection and data model.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct:
    git:
      url: git://github.com/EddieKamau/aqueduct.git
      path: aqueduct

aqueduct_test:
    git:
      url: git://github.com/EddieKamau/aqueduct.git
      path: aqueduct_test