name: wildfire
description: An empty aquedart application.
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

  aquedart: ^5.0.0-b1
  aquedart_test: ^3.0.0

# aquedart:
#     git:
#       url: git://github.com/EddieKamau/aquedart.git
#       path: aquedart

# aquedart_test:
#     git:
#       url: git://github.com/EddieKamau/aquedart.git
#       path: aquedart_test