name: aquedart_test
description: Utilities for writing automated tests for aquedart applications
version: 3.0.0
homepage: https://github.com/EddieKamau/aquedart
documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.3.0
  matcher: '>=0.12.3 <0.14.0'
  aquedart: ^5.0.0-b1
    # path: ../aquedart

# # This is removed before being published.
# dependency_overrides:
#   aquedart:
#     path: ../aquedart