name: wildfire
description: An empty aqueduct application.
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

aqueduct:
    git:
      url: git://github.com/EddieKamau/aqueduct.git
      path: aqueduct

aqueduct_test:
    git:
      url: git://github.com/EddieKamau/aqueduct.git
      path: aqueduct_test